### PR TITLE
Add a feature in slug options to accept transform function

### PR DESCRIPTION
**Pull request by farhantahir**
Implements #18

### CODE REVIEW

**Comment by YuriGor** [comment]
Hi, very cool, thanks for PR!
Could you please add [test](https://github.com/YuriGor/mongoose-slug-updater/tree/master/test) to cover this feature?

**Comment by YuriGor** [comment]
You can get [this one](https://github.com/YuriGor/mongoose-slug-updater/blob/master/test/special.js) as a starting point, but instead of stripping special chars use this new callback feature to strip tags

**Comment by farhantahir** [comment]
@YuriGor Added the test as guided, kindly have a look. Thanks!

**Comment by YuriGor** [comment]
Thank you a lot, your PR published on npm with v3.2.1

**Pull request merged**
